"""Bounded inverse design: enumerate the validated composite design space.

    z ∈ {V_f grid} × {allowed symmetric layups}  →  f(z) (micromechanics + CLT)  →  E(f(z), x*)

This is a transparent grid/enumerative search, not an optimiser: every design
in the bounded set is predicted by the existing physics models and evaluated
by the existing unified evaluator. Nothing is generated by a language model
and no new physics is introduced.

The design target is the part of the user's target the laminate model can
answer: requirements that RESOLVE for ``continuous_fiber_laminate``.
Everything else (strength, failure, corrosion, temperature, water uptake,
direction-less stiffness) is excluded from the search and reported as an
unresolved engineering concern.

Selection order (deterministic): hard-constraint group (feasible first), then
pessimistic distance, then distance, then higher preference coverage, then
the order of the layup in the configured list, then lower V_f.
"""

from __future__ import annotations

import math

from domains.uav_materials.clt import (
    MODEL as LAMINATE_MODEL,
)
from domains.uav_materials.clt import (
    SYSTEM,
    ContinuousFiberLaminateDesignSpace,
    layup_design,
)
from domains.uav_materials.evaluation import CandidateEvaluation, EvaluationContext
from domains.uav_materials.profile import Priority
from domains.uav_materials.requirements import (
    EngineeringTarget,
    RequirementResolver,
)
from domains.uav_materials.schema import MaterialCandidate
from domains.uav_materials.search import GROUP_ORDER, Feasibility
from jevpilot import FrozenModel

SELECTION_RULE = (
    "feasible first; then lower pessimistic distance; then lower distance; then higher "
    "preference coverage; then layup order; then lower fibre volume fraction"
)


class DesignSearchConfig(FrozenModel):
    fiber_id: str = "AS--"
    matrix_id: str = "IMLS"
    fiber_volume_fractions: tuple[float, ...] = (0.50, 0.55, 0.60, 0.65)
    layups: tuple[str, ...] = (
        "0",
        "90",
        "0/90",
        "45/-45",
        "0/45/-45/90",
        "0/0/45/-45",
        "0/60/-60",
    )  # half stacks of symmetric laminates [..]s
    ply_thickness_mm: float = 0.127  # NASA RP-1351 example ply thickness; equal for all plies
    note: str = "bounded enumeration over the validated design space; not an optimiser"


class ExcludedRequirement(FrozenModel):
    requirement: str
    hard: bool
    status: str  # ambiguous / unsupported
    reason: str


class DesignRow(FrozenModel):
    rank: int
    design_id: str
    layup: str
    fiber_volume_fraction: float
    feasibility: str
    violated: tuple[str, ...]
    distance: float | None
    pessimistic_distance: float | None
    coverage: float | None
    properties: dict[str, float]  # density (kg/m^3), laminate Ex/Ey/Gxy (GPa), nuxy


class DesignSearchResult(FrozenModel):
    status: str  # designed | no_feasible_design | no_supported_requirements
    message: str
    config: DesignSearchConfig
    design_target: EngineeringTarget | None
    excluded: tuple[ExcludedRequirement, ...]
    rows: tuple[DesignRow, ...] = ()
    best: MaterialCandidate | None = None  # best-ranked design (feasible or closest)
    best_evaluation: CandidateEvaluation | None = None  # in the design-target context
    model: str = LAMINATE_MODEL.label
    selection_rule: str = SELECTION_RULE


def design_target(
    target: EngineeringTarget,
) -> tuple[EngineeringTarget | None, tuple[ExcludedRequirement, ...]]:
    """The requirements the laminate model can answer, and the excluded rest."""
    resolver = RequirementResolver()
    kept, excluded = [], []
    for r in target.requirements:
        res = resolver.resolve(r, SYSTEM)
        if res.resolved:
            kept.append(r)
        else:
            excluded.append(
                ExcludedRequirement(
                    requirement=r.label,
                    hard=r.priority is Priority.HARD,
                    status=res.status.value,
                    reason=res.reason,
                )
            )
    if not any(r.priority is Priority.HARD for r in kept):
        return None, tuple(excluded)
    return (
        EngineeringTarget(
            profile_id=f"{target.profile_id}:design",
            name="Design target: the requirements the laminate model can answer",
            application=target.application,
            requirements=tuple(kept),
            metadata={"derived_from": target.profile_id},
        ),
        tuple(excluded),
    )


def _properties(candidate: MaterialCandidate) -> dict[str, float]:
    out: dict[str, float] = {}
    for prop, unit in (
        ("density", "kg/m^3"),
        ("laminate_ex", "GPa"),
        ("laminate_ey", "GPa"),
        ("laminate_gxy", "GPa"),
        ("laminate_nuxy", "1"),
    ):
        found = candidate.material.measurements(prop)
        value = found[0].value_in(unit) if found else None
        if value is not None:
            out[prop] = value
    return out


def search_designs(
    target: EngineeringTarget, config: DesignSearchConfig | None = None
) -> DesignSearchResult:
    config = config or DesignSearchConfig()
    goal, excluded = design_target(target)
    if goal is None:
        return DesignSearchResult(
            status="no_supported_requirements",
            message="the composite design space cannot answer any hard requirement of the "
            "request, so no design can be judged",
            config=config,
            design_target=None,
            excluded=excluded,
        )
    space = ContinuousFiberLaminateDesignSpace()
    designs: list[tuple[str, float, MaterialCandidate]] = []
    for layup in config.layups:
        for vf in config.fiber_volume_fractions:
            design = layup_design(
                layup,
                vf=vf,
                ply_thickness_mm=config.ply_thickness_mm,
                fiber=config.fiber_id,
                matrix=config.matrix_id,
                generation_method=f"grid search: layup [{layup}]s x V_f {vf:g}",
            )
            designs.append((layup, vf, space.candidate_from_design(design)))
    context = EvaluationContext.fit(goal, [c for _, _, c in designs])
    evaluated = [(layup, vf, c, context.evaluate(c)) for layup, vf, c in designs]

    def key(item: tuple[str, float, MaterialCandidate, CandidateEvaluation]) -> tuple[float, ...]:
        layup, vf, _, e = item
        inf = math.inf
        # distances are rounded so that mathematically equal designs (e.g. two quasi-isotropic
        # layups) tie exactly and the documented tie-breaks decide, not floating-point noise
        return (
            GROUP_ORDER[e.feasibility],
            round(e.pessimistic_distance, 12) if e.pessimistic_distance is not None else inf,
            round(e.distance, 12) if e.distance is not None else inf,
            -round(e.coverage or 0.0, 12),
            config.layups.index(layup),
            vf,
        )

    evaluated.sort(key=key)
    rows = tuple(
        DesignRow(
            rank=i + 1,
            design_id=c.candidate_id,
            layup=f"[{layup}]s",
            fiber_volume_fraction=vf,
            feasibility=e.feasibility.value,
            violated=e.evidence.violated,
            distance=e.distance,
            pessimistic_distance=e.pessimistic_distance,
            coverage=e.coverage,
            properties=_properties(c),
        )
        for i, (layup, vf, c, e) in enumerate(evaluated)
    )
    _, _, best, best_eval = evaluated[0]
    feasible = best_eval.feasibility is Feasibility.FEASIBLE
    return DesignSearchResult(
        status="designed" if feasible else "no_feasible_design",
        message=(
            f"best of {len(rows)} designs satisfies every design-target hard requirement"
            if feasible
            else f"none of the {len(rows)} designs satisfies every design-target hard "
            "requirement; the closest design is reported, not recommended"
        ),
        config=config,
        design_target=goal,
        excluded=excluded,
        rows=rows,
        best=best,
        best_evaluation=best_eval,
    )
